name: Merge Sprint

on:
  schedule:
    - cron: '0 18 * * 0'  # Runs every Sunday at 8 PM Switzerland time (UTC time: 18:00)
  workflow_dispatch:  # Enable manual triggering of the workflow

env:
  BRANCH_PREFIX: SPRINT_23_CV  # Update with your branch prefix without quotes

jobs:
  merge_sprint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current sprint
        id: current_sprint
        run: |
          CURRENT_SPRINT=echo "::set-output name=sprint::$(cat current_sprint.txt)"
          # Extract the current sprint number from the string
          SPRINT_NUMBER=$(echo "$CURRENT_SPRINT" | sed -n 's/SPRINT_[0-9]*_CV\([0-9]*\)/\1/p')
          echo "::set-output name=sprint::$SPRINT_NUMBER"

      - name: Merge changes from $CURRENT_SPRINT into dev-cicd
        run: |
          git config user.name "Github Action CICD"
          git config user.email "CICD@silverbrain.ai"
          git fetch origin dev-cicd
          git checkout dev-cicd
          git pull origin dev-cicd
          git fetch origin $CURRENT_SPRINT # steps : name of the variable, current_sprint : name of the file, outputs : type of the variable, sprint : name of the variable as declared above
          git merge --allow-unrelated-histories origin/$CURRENT_SPRINT
          git push origin dev-cicd

      - name: Delete current sprint branch
        run: |
          git fetch origin $CURRENT_SPRINT
          git branch -d --remote origin/$CURRENT_SPRINT
          git push origin --delete $CURRENT_SPRINT

      - name: Increment sprint number
        run: |
          # Increment the sprint number
          CURRENT_SPRINT_NUMBER=$CURRENT_SPRINT
          NEXT_SPRINT_NUMBER=$((CURRENT_SPRINT_NUMBER + 1))
          echo $NEXT_SPRINT_NUMBER > current_sprint.txt
          git add current_sprint.txt
          git commit -m "Update current sprint to SPRINT_$NEXT_SPRINT_NUMBER"
          git push origin dev-cicd

      - name: Create a new branch for the next sprint
        run: |
          CURRENT_SPRINT_NUMBER=$CURRENT_SPRINT#*_CV  # Extract the current sprint number
          NEXT_SPRINT_NUMBER=$((CURRENT_SPRINT_NUMBER + 1))  # Increment the sprint number
          NEXT_SPRINT_BRANCH=${{ env.BRANCH_PREFIX }}$NEXT_SPRINT_NUMBER
          git checkout -b $NEXT_SPRINT_BRANCH
          git push origin $NEXT_SPRINT_BRANCH
