name: Merge Sprint

on:
  schedule:
    - cron: '0 18 * * 0'  # Runs every Sunday at 8 PM Switzerland time (UTC time: 18:00)
  workflow_dispatch:  # Enable manual triggering of the workflow

env:
  CURRENT_SPRINT: SPRINT_23_CV39  # Update with the current sprint name including the 'origin/' prefix
  BRANCH_PREFIX: SPRINT_23_CV  # Update with your branch prefix without quotes

jobs:
  merge_sprint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes from $CURRENT_SPRINT into dev-cicd
        run: |
          git config user.name "Github Action CICD"
          git config user.email "CICD@silverbrain.ai"
          git fetch origin dev-cicd
          git checkout dev-cicd
          git pull origin dev-cicd
          git fetch origin $CURRENT_SPRINT
          git merge origin/$CURRENT_SPRINT
          git push origin dev-cicd

      - name: Delete current sprint branch
        run: |
          git fetch origin $CURRENT_SPRINT
          git branch -d --remote origin/$CURRENT_SPRINT
          git push origin --delete $CURRENT_SPRINT

      - name: Create a new branch for the next sprint
        run: |
          CURRENT_SPRINT_NUMBER=${CURRENT_SPRINT#*_CV}  # Extract the current sprint number
          NEXT_SPRINT_NUMBER=$((CURRENT_SPRINT_NUMBER + 1))  # Increment the sprint number
          NEXT_SPRINT_BRANCH=$BRANCH_PREFIX$NEXT_SPRINT_NUMBER  # Include 'origin/' prefix for the remote branch
          git checkout -b $NEXT_SPRINT_BRANCH
          git push origin $NEXT_SPRINT_BRANCH

      - name: Update CURRENT_SPRINT for the next sprint
        run: |
          CURRENT_SPRINT_NUMBER=$((CURRENT_SPRINT_NUMBER + 1))  # Increment the sprint number
          CURRENT_SPRINT=$BRANCH_PREFIX$CURRENT_SPRINT_NUMBER  # Include 'origin/' prefix for the remote branch
          echo "CURRENT_SPRINT=$CURRENT_SPRINT" >> $GITHUB_ENV
