name: Merge Sprint

on:
  schedule:
    - cron: '0 18 * * 0'  # Runs every Sunday at 8 PM Switzerland time (UTC time: 18:00)
  workflow_dispatch:  # Enable manual triggering of the workflow

env:
  BRANCH_PREFIX: SPRINT_23_CV  # Update with your branch prefix without quotes

jobs:
  merge_sprint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current sprint
        id: current_sprint
        run: |
          echo "::set-output name=sprint::$(cat current_sprint.txt)"

      - name: Merge changes from $CURRENT_SPRINT into dev-cicd
        run: |
          git config user.name "Github Action CICD"
          git config user.email "CICD@silverbrain.ai"
          git fetch origin dev-cicd
          git checkout dev-cicd
          git pull origin dev-cicd
          git fetch origin ${{ steps.current_sprint.outputs.sprint }} # steps : name of the variable, current_sprint : name of the file, outputs : type of the variable, sprint : name of the variable as declared above
          git merge --allow-unrelated-histories origin/${{ steps.current_sprint.outputs.sprint }}
          git push origin dev-cicd

      - name: Delete current sprint branch
        run: |
          git fetch origin ${{ steps.current_sprint.outputs.sprint }}
          git branch -d --remote origin/${{ steps.current_sprint.outputs.sprint }}
          git push origin --delete ${{ steps.current_sprint.outputs.sprint }}

      - name: Update current sprint
        run: |
          CURRENT_SPRINT_NUMBER=${${{ steps.current_sprint.outputs.sprint }}#*_CV}  # Extract the current sprint number
          NEXT_SPRINT_NUMBER=$((CURRENT_SPRINT_NUMBER + 1))  # Increment the sprint number
          echo "${{ env.BRANCH_PREFIX }}$NEXT_SPRINT_NUMBER" > current_sprint.txt  # Update the current sprint
          git add current_sprint.txt
          git commit -m "Update current sprint to ${{ env.BRANCH_PREFIX }}$NEXT_SPRINT_NUMBER"
          git push origin dev-cicd

      - name: Create a new branch for the next sprint
        run: |
          CURRENT_SPRINT_NUMBER=${{ steps.current_sprint.outputs.sprint }}#*_CV  # Extract the current sprint number
          NEXT_SPRINT_NUMBER=$((CURRENT_SPRINT_NUMBER + 1))  # Increment the sprint number
          NEXT_SPRINT_BRANCH=${{ env.BRANCH_PREFIX }}$NEXT_SPRINT_NUMBER
          git checkout -b $NEXT_SPRINT_BRANCH
          git push origin $NEXT_SPRINT_BRANCH
